routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\SalesTeamController;
use \App\Http\Controllers\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/info', function () {
    echo phpinfo();
});
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'doLogin'])->name('login');
Route::resource('/sales-team', SalesTeamController::class);

app/Models/SalesTeam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SalesTeam extends Model
{
    use HasFactory;
    protected $table = 'sales_teams';
    protected $primaryKey = 'id';
    protected $fillable = ['full_name', 'email_address', 'telephone_number', 'current_working_route', 'comments', 'joined_date'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AdminLoginRequest;
use Illuminate\Http\Request;
use Auth;
class LoginController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * show the user login form
     */
    public function index()
    {
        return view('login.frm-login');
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     * logout function to redirect logout users to login page
     */

    public function logout()
    {
        Auth::logout();
        return redirect()->to("/login");
    }

    /**
     * @param AdminLoginRequest $request
     * @return \Illuminate\Http\RedirectResponse
     * function to handle admin login request once login pass it will redirect to sales team view page
     */

    public function doLogin(AdminLoginRequest $request)
    {
        $validated = $request->validated();
        $remember = ($request->remember) ? true : false;
        if (!Auth::attempt(array('email' => strtolower($request->email), 'password' => $request->password), $remember)) {
            return redirect()->back()->withErrors(['msg' => 'Invalid email address or password!']);
        }
        return redirect()->to(route("sales-team.index"));
    }
}

app/Http/Controllers/SalesTeamController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SalesTeamCreateRequest;
use App\Http\Requests\SalesTeamUpdateRequest;
use App\Repository\SalesTeamsInterface;
use Illuminate\Http\Request;

class SalesTeamController extends Controller
{
    protected $salesTeam;

    /**
     * SalesTeamController constructor.
     * @param SalesTeamsInterface $salesTeam
     * load the sales team interface
     */
    public function __construct(SalesTeamsInterface $salesTeam)
    {
        $this->middleware('auth');
        $this->salesTeam = $salesTeam;
    }

    /**
     * Display a all the sales team data
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return \view('sales-team.index', [
            'salesTeams' => $this->salesTeam->getAllData()
        ]);
    }

    /**
     * Show the form to create new sales team
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \view('sales-team.create');
    }

    /**
     * Store a newly created sales team in th in the DB table.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(SalesTeamCreateRequest $request)
    {
        $validated = $request->validated();
        $validated['comments'] = $request->comments;
        $this->salesTeam->store($validated);
        return redirect()->route("sales-team.index");
    }

    /**
     * Display the sales team member by id
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->salesTeam->view($id);
        if ($data)
            return response()->json($data);
    }

    /**
     * Show the form to edit the sales team member
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $salesTeam = $this->salesTeam->view($id);
        if ($salesTeam)
            return \view('sales-team.edit', [
                'team' => $salesTeam
            ]);


    }

    /**
     * Update the specified sales member in the DB table
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(SalesTeamUpdateRequest $request, $id)
    {
        $validated = $request->validated();
        $validated['comments'] = $request->comments;
        $this->salesTeam->update($id, $validated);
        return redirect()->route("sales-team.index");

    }

    /**
     * Remove the specified sales member from DB table.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->salesTeam->delete($id);
    }
}

resources/views/layouts/app/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <title>EyePax | Sale Manager</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{{url("css/all.min.css")}}">
    <link rel="stylesheet" href="{{url('/css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{url('/css/tempusdominus-bootstrap-4.min.css')}}">
    <link rel="stylesheet" href="{{url("/css/icheck-bootstrap.min.css")}}">
    <link rel="stylesheet" href="{{url('/css/adminlte.min.css')}}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png" alt="AdminLTELogo"
             height="60" width="60">
    </div>

    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a href="{{route('logout')}}">Logout</a>
            </li>
        </ul>
    </nav>
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
            <img src="https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Sale Manager</span>
        </a>
        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="https://adminlte.io/themes/v3/dist/img/user2-160x160.jpg" class="img-circle elevation-2"
                         alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{Auth::user()->name}}</a>
                </div>
            </div>
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <p>Sales Team</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                @yield('content')
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.1.0
        </div>
    </footer>
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<!-- jQuery -->
<script src="https://adminlte.io/themes/v3/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://adminlte.io/themes/v3/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{url("/js/jquery.min.js")}}"></script>
<script src="{{url('/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{url('/js/jquery.overlayScrollbars.min.js')}}"></script>
<script src="{{url('/js/adminlte.js')}}"></script>
@stack('scripts')
</body>
</html>

resources/views/login/frm-login.blade.php
@extends('layouts.auth.layout')
@section('content')
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                @if($errors->any())
                    <div class="alert alert-danger alert-dismissible">
                        <h5>Alert!</h5>
                        {{$errors->first()}}
                    </div>
                @endif

                <p class="login-box-msg">Admin Login</p>
                <form action="{{route("login")}}" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" name="email" class="form-control" id="exampleInputEmail1"
                               placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputEmail1"
                               placeholder="Enter password">
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                            <input type="checkbox" id="remember" name="remember">
                                <label for="remember">
                                   Remember Me
                                </label>
                            </div>
                        </div>
                        <div class="col-4">
                            @csrf
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/sales-team/create.blade.php
@extends('layouts.app.layout')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Sales Team</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href={{route("sales-team.index")}}#">Sales Team</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add New Sale Team</h3>
                            <br>
                        </div>
                        <form name="add-sales-team" method="post" action="{{route('sales-team.store')}}">
                            <div class="card-body">
                                @if($errors->any())
                                    <div class="alert alert-danger alert-dismissible">
                                        <h5>Error!</h5>
                                        @if($errors->any())
                                            {!! implode('', $errors->all('<div>:message</div>')) !!}
                                        @endif
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label>Full Name</label>
                                    <input type="text" class="form-control"
                                           placeholder="" name="full_name" value="{{old('full_name')}}">
                                </div>
                                <div class="form-group">
                                    <label>Email address</label>
                                    <input type="email" class="form-control"
                                           name="email_address" value="{{old('email_address')}}">
                                </div>
                                <div class="form-group">
                                    <label>Telephone Number</label>
                                    <input type="text" class="form-control" name="telephone_number"
                                           value="{{old('telephone_number')}}">
                                </div>
                                <div class="form-group">
                                    <label>Current Working Route</label>
                                    <input type="text" class="form-control" name="current_working_route"
                                           value="{{old('current_working_route')}}">
                                </div>
                                <div class="form-group">
                                    <label>Comments</label>
                                    <textarea class="form-control" name="comments">{{old('comments')}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Joined Date</label>
                                    <input type="text" class="form-control" placeholder="yyyy-mm-dd" name="joined_date"
                                           value="{{old('joined_date')}}">
                                </div>
                            </div>
                            <div class="card-footer">
                                @csrf
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection

resources/views/sales-team/edit.blade.php
@extends('layouts.app.layout')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Sales Team</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href={{route("sales-team.index")}}#">Sales Team</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Update Sale Team</h3>
                            <br>
                        </div>
                        <form method="POST" action="{{route('sales-team.update', ['sales_team' => $team->id])}}">
                            <div class="card-body">
                                @if($errors->any())
                                    <div class="alert alert-danger alert-dismissible">
                                        <h5>Error!</h5>
                                        @if($errors->any())
                                            {!! implode('', $errors->all('<div>:message</div>')) !!}
                                        @endif
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label>Full Name</label>
                                    <input type="text" class="form-control"
                                           placeholder="" name="full_name" value="{{$team->full_name}}">
                                </div>
                                <div class="form-group">
                                    <label>Email address</label>
                                    <input type="email" class="form-control"
                                           name="email_address" value="{{$team->email_address}}">
                                </div>
                                <div class="form-group">
                                    <label>Telephone Number</label>
                                    <input type="text" class="form-control" name="telephone_number"
                                           value=" {{$team->telephone_number}}">
                                </div>
                                <div class="form-group">
                                    <label>Current Working Route</label>
                                    <input type="text" class="form-control" name="current_working_route"
                                           value="{{$team->current_working_route}}">
                                </div>
                                <div class="form-group">
                                    <label>Comments</label>
                                    <textarea class="form-control" name="comments">{{$team->comments}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Joined Date</label>
                                    <input type="text" class="form-control" placeholder="yyyy-mm-dd" name="joined_date"
                                           value="{{$team->joined_date}}">
                                </div>
                            </div>
                            <div class="card-footer">
                                @csrf
                                {{ method_field('PUT') }}
                                <input type="hidden" name="id" value="{{$team->id}}">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection

resources/views/sales-team/index.blade.php
@extends('layouts.app.layout')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Sales Team</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Sales Team</li>
            </ol>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-header text-right">
                            <a href="{{route("sales-team.create")}}" class="btn btn-primary btn-sm">Add New</a>
                        </div>
                        <div class="card-body">
                            <div id="" class="dataTables_wrapper dt-bootstrap4">
                                <table id="example1"
                                       class="table table-bordered table-striped dataTable dtr-inline"
                                       role="grid" aria-describedby="example1_info">
                                    <tbody>
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Full Name</th>
                                        <th>Email Address</th>
                                        <th>Telephone Number</th>
                                        <th>Route</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    @forelse($salesTeams as $key => $team)
                                        <tr>
                                            <td>{{$team->id}}</td>
                                            <td>{{$team->full_name}}</td>
                                            <td>{{$team->email_address}}</td>
                                            <td>{{$team->telephone_number}}</td>
                                            <td>{{$team->current_working_route}}</td>
                                            <td>
                                                <a href="#"
                                                   class="btn btn-sm btn-primary view-team"
                                                   data-id="{{$team->id}}">View</a>

                                                <a href="{{route('sales-team.edit',$team->id)}}"
                                                   class="btn btn-sm btn-info">Edit</a>

                                                <a href="#"
                                                   class="btn btn-sm btn-danger delete-team" data-id="{{$team->id}}"
                                                   data-name="{{$team->full_name}}">Delete</a>

                                            </td>
                                        </tr>
                                        @empty
                                        @endforelse
                                        </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table table-striped">
                        <tr>
                            <td>ID</td>
                            <td class="view-id"></td>
                        </tr>
                        <tr>
                            <td>Full Name</td>
                            <td class="view-fname"></td>
                        </tr>
                        <tr>
                            <td>Email Address</td>
                            <td class="view-email"></td>
                        </tr>
                        <tr>
                            <td>Telephone</td>
                            <td class="view-telephone"></td>
                        </tr>

                        <tr>
                            <td>Joined Date</td>
                            <td class="view-joindate"></td>
                        </tr>

                        <tr>
                            <td>Current Route</td>
                            <td class="view-route"></td>
                        </tr>

                        <tr>
                            <td>Comments</td>
                            <td class="view-comments"></td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        /**
         * Ajax call to delete the sales member
         */
        $(document).on("click", ".delete-team", function () {
            var full_name = $(this).attr("data-name");
            var result = confirm("Want to delete " + full_name + "?");
            if (result) {
                var id = $(this).data("id");
                var token = $("meta[name='csrf-token']").attr("content");
                $.ajax(
                    {
                        url: "sales-team/" + id,
                        type: 'DELETE',
                        data: {
                            "id": id,
                            "_token": token,
                        },
                        success: function () {
                            window.location = "{{route('sales-team.index')}}"
                        }
                    });

            }
        });

        /**
         * Ajax call to get sale member data to the pop up view
         */
        $(document).on("click", ".view-team", function () {
            var id = $(this).data("id");
            var token = $("meta[name='csrf-token']").attr("content");
            $.ajax(
                {
                    url: "sales-team/" + id,
                    type: 'GET',
                    data: {
                        "id": id,
                        "_token": token,
                    },
                    success: function (response) {
                        $(".modal-title").text(response.full_name)
                        $("td.view-id").text(response.id)
                        $("td.view-fname").text(response.full_name)
                        $("td.view-email").text(response.email_address)
                        $("td.view-telephone").text(response.telephone_number)
                        $("td.view-joindate").text(response.joined_date)
                        $("td.view-route").text(response.current_working_route)
                        $("td.view-comments").text(response.comments)
                        $("#modal-default").modal('show');
                    }
                });


        });
    </script>
@endpush